---
book_repo: pivotal-cf/docs-book-pivotalcf
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'edge'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

products:
  - id: pcf-dev
    subnav_root: pcf-dev/index.html

pcf_header: &local_pcf
  use_local_header: true
  latest_stable_version: '2.0'
  changelog_href: https://docs.pivotal.io/pivotalcf/pcf-release-notes/
  local_header_img: /images/cloud_rings.png
  local_header_title: Pivotal Cloud Foundry
  search_placeholder: Search PCF 2.0
  local_product_version: '2.0'
  url_prefix: pivotalcf/2-0
  local_header_links:
    - <a href="https://network.pivotal.io/">Download</a>
    - <a href="https://support.pivotal.io/hc/en-us/requests/new">Ask for Help</a>
    - <a href="https://discuss.pivotal.io/hc/en-us/categories/200072648-Pivotal-CF-Knowledge-Base">PCF Knowledge Base</a>
    # - <a href="/archives/pcf-docs-2.0.pdf">PDF</a>
  local_header_version_list:
    - url_prefix: https://docs.pivotal.io/pivotalcf/1-12
      display_name: v1.12
    - url_prefix: https://docs.pivotal.io/pivotalcf/1-11
      display_name: v1.11
    - url_prefix: https://docs.pivotal.io/pivotalcf/1-10
      display_name: v1.10
    - url_prefix: https://docs.pivotal.io/pivotalcf/1-9
      display_name: v1.9
    - url_prefix: https://docs.pivotal.io/pivotalcf/1-8
      display_name: v1.8
    - url_prefix: https://docs.pivotal.io/pivotalcf/1-7
      display_name: v1.7
    - url_prefix: https://docs.pivotal.io/pivotalcf/1-6
      display_name: v1.6
    - <a href="/archives/pcf-docs-1.5.pdf">v1.5</a>
    - <a href="/archives/pcf-docs-1.4.pdf">v1.4</a>
    - <a href="/archives/pcf-docs-1.3.pdf">v1.3</a>
    - <a href="/archives/pcf-docs-1.2.pdf">v1.2</a>

sections:
# pivotalcf repos: alphabetical within org cloudfoundry
- repository:
    name: cloudfoundry/docs-buildpacks
  directory: pivotalcf/2-0/buildpacks
  subnav_template: security.erb
  product_info: *local_pcf
  dependent_sections:
  - repository:
      name: cloudfoundry-samples/pong_matcher_grails
    no_docs: true
  - repository:
      name: cloudfoundry-samples/pong_matcher_groovy
    no_docs: true
  - repository:
      name: cloudfoundry-samples/pong_matcher_spring
    no_docs: true
  - repository:
      name: cloudfoundry-samples/pong_matcher_ruby
    no_docs: true
- repository:
    name: cloudfoundry/docs-cf-admin
  directory: pivotalcf/2-0/adminguide
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: cloudfoundry/docs-cf-cli
  directory: pivotalcf/2-0/cf-cli
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: cloudfoundry/docs-cloudfoundry-concepts
  directory: pivotalcf/2-0/concepts
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: cloudfoundry/docs-credhub
  directory: pivotalcf/2-0/credhub
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: cloudfoundry/docs-dev-guide
  directory: pivotalcf/2-0/devguide
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: cloudfoundry/docs-loggregator
  directory: pivotalcf/2-0/loggregator
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: pivotal-cf/docs-monitoring
    at_path: docs-content
  directory: pivotalcf/2-0/monitoring
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: pivotal-cf/docs-pas
  directory: pivotalcf/2-0/pas
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: cloudfoundry/docs-routing
  directory: pivotalcf/2-0/routing
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: cloudfoundry/docs-services
  directory: pivotalcf/2-0/services
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: cloudfoundry/docs-uaa
  directory: pivotalcf/2-0/uaa
  subnav_template: security.erb
  product_info: *local_pcf

# pivotalcf repos: alphabetical within org pivotal-cf
- repository:
    name: pivotal-cf/docs-ops-guide
  directory: pivotalcf/2-0/opsguide
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: pivotal-cf/docs-pcf-dev
  directory: pcf-dev
  subnav_template: pivotal_pcfdev_subnav.erb
- repository:
    name: pivotal-cf/docs-pcf-gsg
  directory: pivotalcf/2-0/installing
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: pivotal-cf/docs-pcf-install
  directory: pivotalcf/2-0/customizing
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: pivotal-cf/docs-pcf-pws
  directory: pivotalcf/2-0/appsman-services
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: pivotal-cf/docs-pcf-refarch
  directory: pivotalcf/2-0/refarch
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: pivotal-cf/docs-pcf-security
  directory: pivotalcf/2-0/security
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: pivotal-cf/docs-pcf-windows
    at_path: docs-content
  directory: pivotalcf/2-0/windows
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: pivotal-cf/docs-pcf-windows2012r2
    at_path: docs-content
  directory: pivotalcf/2-0/windows2012r2
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: pivotal-cf/docs-pivotalcf-console
  directory: pivotalcf/2-0/console
  subnav_template: security.erb
  product_info: *local_pcf
- repository:
    name: pivotal-cf/pcf-release-notes
    ref: '2.0'
  directory: pivotalcf/2-0/pcf-release-notes
  subnav_template: security.erb
  product_info: *local_pcf

# cross-product resources
- repository:
    name: pivotal-cf/docs-pdfs
  directory: archives
- repository:
    name: pivotal-cf/product-compatibility-matrix
  directory: resources
  subnav_template: security.erb
